### ISSUE TITLE
YAML fragment: is switching from named anchor to alias nodes seamles?

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/mediatypes#41]
## Question

Currently the spec supports fragment identifier based on "named anchors", e.g. `foo.yaml#ant` references `one`.

```
# This is foo.yaml
one: &ant one
```

Today alias nodes syntax is  [just `*` +  named anchors](https://yaml.org/spec/1.2.2/#alias-nodes), 

```
one: &named_anchor one
alias_node: *named_anchor
```

but in the future alias nodes could support "pathlike" expressions,
e.g. `*foo/bar`.

Can "named anchors" fragment identifiers be extended  in the future in a backward compatible way to suppot "alias nodes" syntax? 

### Pathlike alias nodes are complex

Consider the following examples

1. `/` is a valid character for a named anchor, using `/`  as a pathlike separator might be non-trivial. Currently many YAML parser do only support `[a-zA-Z0-9-_]` though, so future YAML spec might restrict the syntax of named anchors

```yaml
- par: &ant/ani ciao
- rap: *ant/ani
```
2. keys might contain  non-string characters (e.g. `1` vs `"1"`). We need to know how pathlike elements are serialized, to identify a human-readable encoding (e.g. JSON Pointer)

```yaml
- &foo
  bar:
    1: "integer"
   "1": "string"
  '"1"': '"1"'
- baz: 
  - *foo/bar/1
  - *foo/bar/"1"
  - *foo/bar/"\"1\""
```

3. another example. A non human-readable encoding such as base64url would solve the issue, since we could just decode the string. This could be supported when pathlike are messy, e.g. `file.yaml#:Zml6ei8iYnV6ei9iYXo=:`

```yaml
- &fizz
  "buzz/baz": "a"
  "buzz":
    "baz": "b"
- roc: *fizz/buzz/baz
- rov: *fizz/"buzz/baz"
```
